// src/app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import Navbar from '../components/Navbar'; // Update import to Navbar

export const metadata: Metadata = {
  title: "David IG",
  description: "Generated by Davidko",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <body style={{ paddingBottom: '56px' }}> {/* Padding for Navbar */}
        {children}
        <Navbar /> {/* Include the Navbar */}
      </body>
    </html>
  );
}
